import React, { useState, useCallback } from 'react';
import { generateImageWithAI, isAiAvailable } from '../services/geminiService';
import { ArrowPathIcon, ImageIcon, WandSparklesIcon } from './icons';

const ImageGenerator: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [aiReady] = useState(() => isAiAvailable());

  const processGeneration = useCallback(async () => {
    if (!prompt) {
      setError('Please provide a prompt to generate an image.');
      return;
    }
    setIsLoading(true);
    setGeneratedImage(null);
    setError(null);
    try {
      const result = await generateImageWithAI(prompt);
      if (result) {
        setGeneratedImage(`data:image/png;base64,${result}`);
      } else {
        throw new Error("Received no image data");
      }
    } catch (err: any) {
      setError(err.message || 'Failed to generate image. The model might be unavailable. Please try again later.');
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  }, [prompt]);
  
  const examplePrompts = ["A modern minimalist house in a forest, hyperrealistic", "An eco-friendly skyscraper covered in plants, blueprint style", "Interior of a cozy cabin with a fireplace, warm lighting"];


  return (
    <div className="bg-brand-blue-dark/50 backdrop-blur-lg border border-brand-blue-light rounded-xl shadow-2xl p-6 h-full flex flex-col relative">
       {!aiReady && (
        <div className="absolute inset-0 bg-brand-blue-dark/90 flex flex-col items-center justify-center rounded-xl z-10 p-4">
            <ImageIcon className="w-16 h-16 text-amber-500/50 mb-4" />
            <h3 className="text-xl font-jura font-bold text-amber-400 text-center">AI Generator Unavailable</h3>
            <p className="text-slate-400 text-center mt-2">To use this feature, please set the <code className="bg-brand-blue-dark p-1 rounded">API_KEY</code> environment variable and redeploy the application.</p>
        </div>
      )}
      <div className="flex items-center gap-2 mb-4">
        <ImageIcon className="w-6 h-6 text-brand-gold" />
        <h3 className="text-xl font-jura text-white">AI Image Generator</h3>
      </div>
      <div className="flex flex-col gap-4 flex-grow">
        <div className="relative border-2 border-dashed border-brand-blue-light rounded-lg h-full flex items-center justify-center text-slate-400 bg-brand-blue-dark/40 min-h-[300px]">
          {isLoading && (
             <div className="flex flex-col items-center gap-2 text-brand-gold">
              <ArrowPathIcon className="w-12 h-12 animate-spin" />
              <p>Archigen AI is creating...</p>
            </div>
          )}
          {generatedImage && !isLoading && (
            <img src={generatedImage} alt="Generated by AI" className="max-h-full max-w-full object-contain rounded-lg" />
          )}
          {!generatedImage && !isLoading && (
            <div className="text-center">
              <ImageIcon className="w-12 h-12 mx-auto" />
              <p>Your generated image will appear here</p>
            </div>
          )}
          {error && !isLoading && <p className="absolute bottom-4 text-red-500">{error}</p>}
        </div>
         <div className="flex flex-wrap gap-2">
            {examplePrompts.map(p => (
              <button key={p} onClick={() => setPrompt(p)} className="text-xs bg-brand-blue hover:bg-brand-blue-light text-slate-200 px-2 py-1 rounded-md transition-colors">{p}</button>
            ))}
          </div>
        <div className="flex gap-4">
          <input
            type="text"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="e.g., 'A futuristic city skyline at dawn'"
            className="w-full bg-brand-blue-dark/50 p-3 rounded-lg focus:outline-none focus:ring-2 focus:ring-brand-gold text-white"
          />
          <button
            onClick={processGeneration}
            disabled={isLoading || !prompt}
            className="bg-brand-gold text-brand-blue-dark font-bold py-3 px-6 rounded-lg hover:bg-brand-gold-light disabled:bg-slate-600 disabled:cursor-not-allowed transition-all duration-300 hover:shadow-lg hover:shadow-brand-gold/20 flex items-center justify-center gap-2"
          >
            {isLoading ? <ArrowPathIcon className="w-5 h-5 animate-spin" /> : <WandSparklesIcon className="w-5 h-5" />}
            Generate
          </button>
        </div>
      </div>
    </div>
  );
};

export default ImageGenerator;